=== SticsRPacks/SticsRTests/stics/JavaSTICS-1.41-stics-9.0-light/bin/resources/xml/MenuML.dtd
<!ELEMENT MENUBAR (MENU)+>
<!ELEMENT MENU (MENU|MENU-ITEM|MENU-ITEM-CHECKBOX)+>
<!ATTLIST MENU
          name CDATA #REQUIRED>          
<!ELEMENT MENU-ITEM EMPTY>
<!ATTLIST MENU-ITEM
          name CDATA #REQUIRED
          action CDATA #IMPLIED
          image  CDATA #IMPLIED>
<!ELEMENT MENU-ITEM-CHECKBOX EMPTY>
<!ATTLIST MENU-ITEM-CHECKBOX
          name CDATA #REQUIRED
          action CDATA #IMPLIED
          image  CDATA #IMPLIED
          groupe CDATA #IMPLIED>

=== SticsRPacks/SticsRTests/stics/JavaSTICS-1.41-stics-9.0/bin/resources/xml/MenuMLEn.xml
<?xml version='1.0' ?> 
<!DOCTYPE MENUBAR SYSTEM "MenuML.dtd">

<MENUBAR>
        <MENU name="Workspace">
                <MENU-ITEM name="Open / New" image="stics/resources/shared/images/menu/file/Open16.gif" action="repertoire" />
                <MENU-ITEM name="Exit" action="quitter" />
        </MENU>
        <MENU name="Inputs">
                <MENU-ITEM name="Parameters" action="parametres" />
                 <MENU-ITEM name="Initialisations" action="initialisations" />
        			<MENU-ITEM name="Sols" action="sols" />
                <MENU-ITEM name="LAI" action="lai" />
                <MENU-ITEM name="Climatic" action="climat" />
                <MENU-ITEM name="Observed data" action="obs" />
        </MENU>
        <MENU name="Models">
         		<MENU-ITEM name="Models (select / add)"  action="choixmodele" />
                <MENU-ITEM name="Working files for associated or pure USM Corp" action="choixusm" />
                <MENU name="Choice of output variables" >
        			<MENU-ITEM name="Daily output" action="choixsorties" />
        			<MENU-ITEM name="Report" action="rapport" />
        			<MENU-ITEM name="Profile" action="profil" />
        		</MENU>
                <MENU-ITEM name="Run" action="executer"/>
                <MENU-ITEM name="Optimise" action="optimiser"/>
                <MENU-ITEM name="Sequence of several USM" action="grouper"/>
                <MENU-ITEM name="Enchainer plusieurs USM(mais en anglais)" action="enchainer" />
        </MENU>
        <MENU name="Outputs">
                <MENU-ITEM name="View Variables" action="visuvars"/>
                <MENU-ITEM name="View Profile" action="visuprofil"/>
                <MENU-ITEM name="Statistics" action="statistiques"/>
        </MENU>
        <MENU name="File">
                <MENU-ITEM name="Open" image="stics/resources/shared/images/menu/file/Open16.gif" action="fichier_ouvrir"/>
                <MENU-ITEM name="Close" image="stics/resources/shared/images/menu/file/Delete16.gif" action="fichier_fermer"/>
                <MENU-ITEM name="Save As" image="stics/resources/shared/images/menu/file/SaveAs16.gif" action="fichier_enregistrer"/>
                <MENU-ITEM name="Page Setup... " image="stics/resources/shared/images/menu/file/PageSetup16.gif" action="fichier_miseenpage"/>
                <MENU-ITEM name="Print" image="stics/resources/shared/images/menu/file/Print16.gif" action="fichier_imprimer"/>
        </MENU>
        <MENU name="Tools">
                <MENU name="View">
                        <MENU-ITEM name="Java" action="style_java" />
                        <MENU-ITEM name="Windows" action="style_windows"/>
                        <MENU-ITEM name="Motif" action="style_motif"/>
                </MENU>
                <MENU-ITEM name="Preferences" action="preferences" />
        		<MENU-ITEM-CHECKBOX name="tool bar" action="barre_outils" groupe="" />
       			 <MENU-ITEM-CHECKBOX name="state bar" action="barre_etat" groupe="" />
        	<MENU name="Tools for putting in the format">
          		<MENU-ITEM name="V6.2 -> V7.0 of directory(ies) ... " action="convertRep2Xml" />
          		<MENU name="V6.2 -> V7.0 of file(s) ...">
          			<MENU-ITEM name="Convert file .plt en .xml" action="convertPlt2Xml" />
          			<MENU-ITEM name="Convert file .tec en .xml" action="convertTec2Xml" />
          			<MENU-ITEM name="Convert file of generals parameters in .xml" action="convertParamGen2Xml" />
          			<MENU-ITEM name="Convert file of daily outputs in .xml" action="convertTtoXml" />
          			<MENU-ITEM name="Convert old files usm in .xml" action="convertUSMtoXml" />
          		</MENU> 
        	</MENU>     
        </MENU>
        <MENU name="Help">
                <MENU-ITEM name="Shortcuts" image="stics/resources/shared/images/menu/help/Help16.gif"/>
                <MENU-ITEM name="About Stics" image="stics/resources/shared/images/menu/help/About16.gif" action="apropos" />
        </MENU>
</MENUBAR>
